### ISSUE TITLE
Coinapult locks or not?

### ISSUE THREAD

**Issue by ghost** [hivewallet/discussions#27]
The Coinapult "Locks" system provides a Bridgewalker-type service, and looks pretty clean. The major issue behind it seem to be that it is entirely controlled by a third party... Which is no different than Bridgewalker, for sure.

What's the safest way to implement something like this? What kind of messages should we give the user to warn them about the potential risks?

**Comment by javgh** [comment]
I think this is probably fairly low-priority, right? It would have to be optional and can also only be offered to non-US-users, if I remember Coinapult's ToS correctly. It could work well as an app, I would think, assuming we still have the Hive API: You install a Coinapult lock app, then can move things in and out of your fiat-based vault there.
