### ISSUE TITLE
Missing transaction

### ISSUE THREAD

**Issue by jvamos** [hivewallet/discussions#28]
Hello,

I had a transfer from blockchain.info go missing. I used the shared send function. Blockchain.info support has confirmed the transfer has gone to the wallet but I never received it. I tried a normal transfer afterward for a dollar and the wallet works. Any idea how to restore a lost transfer? How can I visually see where the money is beyond the links support has sent me?

Thanks

**Comment by javgh** [comment]
Hi there,

sorry to hear you are having troubles with a transaction. Which of our wallets are you using? Hive OS X, Hive Android or Hive Web? If you don't mind, it would also be helpful if you could share the Bitcoin address you used either here or via e-mail to support@hivewallet.com, then we can look into it.

Either way though, I'm fairly sure any funds can be recovered. Simply waiting a few hours might also help - it might be, that the transaction has not propagated properly yet.

**Comment by jvamos** [comment]
Hi,
Thanks for your help Javgh. it was over a week ago. I did email support but haven't heard back since I sent my logs in. I can resend them if you wish. I think I used the mac support email as I am using OS X I just stopped by a place where BTC is incubated as it were in Toronto. I was assured other apps can open the wallet and find transactions that were not synced. I am hoping he is right. 
Should I continue by using the Mac support address? I am really looking forward to getting this solved.

**Comment by jvamos** [comment]
I have sent the links to the above email address. I can forward logs if necessary as well. I got that sinking feeling when I saw the coins leave and not return. More so when I was told by blockchain.info they were gone and had been transferred to the wallet. I am not really knowledgeable when it comes to the workings of bitcoin and the blockchain, moving private keys is a bit scary for me. I don't really know where else to turn to for help at this point. 
Thanks again

**Comment by javgh** [comment]
I'll let @jsuder handle this, as he is working on Hive OS X.

But if the Bitcoin address you see in Hive OS X is the one you sent via e-mail, than there is definitely a way to get to your funds. We'll just have to figure out the easiest way to go about it.

**Comment by mackuba** [comment]
Hi,

sorry for the delay, I'll respond via email in a moment. I'm closing this ticket because this repository is for general strategic planning and such things. Ping me in that email thread later if I forget.
