### ISSUE TITLE
I can't find any instructions how to restore an android backup on a new device.

### ISSUE THREAD

**Issue by passdan** [hivewallet/discussions#29]
I know github issues isn't the right place for this per se, but I can't find a support email address.

I have a backup from my android wallet from months ago, before the HD wallets took over. Now I broke the phone and want to restore hive onto my android tablet, but I can't see an import function or any instructions on how to do this, even on the wiki.

Can anyone help me out here?

**Comment by mackuba** [comment]
ping @javgh

**Comment by KBenavidez** [comment]
Hi passdan, you might want to read this FAQ on restoring your android wallet : https://github.com/hivewallet/hive-android/wiki/FAQ#how-will-i-restore-my-wallet

**Comment by javgh** [comment]
Hi there! You can still install the "old", pre-HD wallet app on Android. Here is the link to the app on Google Play: https://play.google.com/store/apps/details?id=com.hivewallet.androidclient.wallet .

Then you should be able to restore as per the FAQ entry Karla posted. Where do you have your backup file? A little while ago we reduced the number of permissions the app needs drastically, which means it can also no longer access your SD card. You will need to have the backup file in your Google Drive or Dropbox folder. Usually it works best if you "browse" to wherever your file is, tap it and Android should suggest Hive Android Legacy as one of the actions.

Let me know if you run into any problems. Through all the migrations, the backup situation has gotten a bit hairy unfortunately. But in the worst case your keys can always be extracted manually.

**Comment by passdan** [comment]
Ah, I didn't realise that there are two hive apps on the play store. I searched and installed the first, and assumed that everything had been moved to the new one. I have recovered my wallet into the old app now and all is good.

To be honest, it's really not clear. There is nothing to discern between the two apps on my device (same icon, same name) and there's nothing on the play store saying "This is the older version, you should install this one" or even Hive HD.

**Comment by javgh** [comment]
The old app should have the label "Hive Legacy". But you are right, it isn't clear at all from the Google Play entry. I'll update those - thanks for the feedback!
