### ISSUE TITLE
XMLHttpRequest Error

### ISSUE THREAD

**Issue by Oaklandish** [hivewallet/discussions#31]
I'm accessing the hive using https://web.hivewallet.com

I can't login to one of my wallets, after entering the passphrase and PIN number, the following error pops up 
![capture](https://cloud.githubusercontent.com/assets/12978300/8269093/e346762a-17af-11e5-9de3-277f0e00ab49.JPG)

why this happens?
PS. this error only occurs in one specific wallet, I still can login into other wallets, using different passphrases, on the very same laptop/browser. so it seems like an bug or something.

**Comment by ghost** [comment]
Yes sorry, this is a known problem related to API server timeouts with "heavily" used wallets. See here:

https://github.com/hivewallet/hive-js/issues/233#issuecomment-113821036

**Comment by ghost** [comment]
To be clear: we're glad to finally know what the problem is (very difficult to diagnose when we have zero access to peoples' wallets), but we probably won't be able to issue a fix until next month. If you don't mind, please reply in the thread linked above if you have any more comments about it.

**Comment by ghost** [comment]
Please try http://hive-js.herokuapp.com with your passphrase and let us know if it works.

**Comment by Oaklandish** [comment]
visited there, and to my surprise it asked me to set a new pin after entering my pin and it told me it's wrong !
Anyway, I set a new PIN and then again, the same Error : XMLHttpRequestError

**Comment by ghost** [comment]
@Oaklandish where are you located? We're slowly figuring out that this has _something_ to do with latency in connections.

**Comment by Oaklandish** [comment]
I'm from Iran, And using a Proxy server which is actually located in Fremont, California
and this problem is occurring even when i'm not using the Proxy server.
By the way my net speed is 512 Kb/s and my download rate is 80 Kb/s average with a minimum of 60 Kb/s.

**Comment by ghost** [comment]
Interesting. Can you try pinging hive-js.herokuapp.com from both your proxied and non-proxied state, and post the results here?

**Comment by Oaklandish** [comment]
WAIT, I just logged in to my account again :O
don't know why but right now it worked.
does it mean it's resolved permanently or just temporarily ?

**Comment by Oaklandish** [comment]
and my Name and Gravatar email are gone !

**Comment by ghost** [comment]
Name and gravatar are gone because it is on a different server.

But that's promising news! Can you try logging out and back in again, a few times? Sounds like we may be close to a solution for most people.

**Comment by Oaklandish** [comment]
yes, logged out and in several times, with and without proxy, It's just working fine.
hope it stays in this situation forever :smile:

**Comment by ghost** [comment]
Great. We're going to do some more work on this and will move it to the main web.hivewallet.com server when it's stable.

**Comment by Oaklandish** [comment]
So you know what was the reason and what did you change just right now to make it work again ?

**Comment by ghost** [comment]
The issue is latency, and @weilu reduced the payload.
