### ISSUE TITLE
How to completely remove Hive Wallet and/or individual app

### ISSUE THREAD

**Issue by jckseouljah87** [hivewallet/discussions#4]
How do I completely remove Hive so that if I re-install it, it creates a new wallet.
I tried deleting the associated plist files in my Library but it didn't work.

I also want to delete certain apps from the applications menu as well but there's no option.

**Comment by weilu** [comment]
All Hive apps are inside `~/Library/Application Support/Hive/Applications/` You can delete apps directly from there and go to the top menu: Tools > Debugging Tools > Rebuild application list.

May I ask why you wish to delete certain apps? Let us know if some apps are not working as expected. We'll fix them or remove them from app store.

**Comment by jckseouljah87** [comment]
I'm having issues with the coinbase App not being able to link to my account. Log shows request to the coinbase API is failing. I messed around with it and I can't get it to work anymore.

**Comment by jckseouljah87** [comment]
I found the wallet files and plist files and deleted them. created a new wallet with a new password. But when I click on the apps, they log in automatically to my accounts, i.e. bitstamp, etc. I don't know where these files are located on my machine. I just want to be able to delete and fresh install them. Also, kind of concerning that the new wallet was able to log-in to these accounts without asking for passwords, etc.

**Comment by mackuba** [comment]
Responded here: https://github.com/hivewallet/hiveapp-coinbase/issues/8
Moved ticket to hive-osx: https://github.com/hivewallet/hive-osx/issues/343

As for removing apps from the list, you can do that now by right-clicking an app and selecting delete from the context menu (though it doesn't erase the data).

**Comment by mackuba** [comment]
Clearing application data will be available in the next version (right-click menu item on app icon, cookies automatically deleted when an app is uninstalled, and a button in "Debugging tools" to delete cookies from all apps).

BTW, we'll be removing apps from Hive completely in the nearest future (https://github.com/hivewallet/hive-osx/issues/439).
